name: teamtask_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.10
  shared_preferences: ^2.2.2
  # the annotation package containing @riverpod
  riverpod_annotation: 2.3.1
  auto_route: 7.8.4
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: 2.3.6
  auto_route_generator: 7.3.2

flutter:
  uses-material-design: true
  # assets:
